name: Update JSON

on:
  push:
    branches:
      - main

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Git Config
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Update JSON Files
        run: |
          git add songs.json images.json
          git commit -m "Update JSON files" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/Aditya-Nikam/Spotify.git
